### PR TITLE
Reloaded database

### PR DESCRIPTION
**Pull request by ind1010**
I have reloaded all data except dining and cafes. Removed vending machines since locations are not longer available.

### CODE REVIEW

**Comment by ind1010** [comment]
Need to check something so closing this pull request.

**Comment by nicholaspad** [comment]
Thanks for doing this! Let me know when you've restored dining halls and cafes. Also, do you want to remove vending machines from the UI since they're no longer available?
image

**Comment by ind1010** [comment]
Yes, I removed the Vending Machines label in this branch

We'll also be adding the room + floor for printers/scanners/computers in this same branch since I noticed that we had collected the data. This was originally the intent of the printer-info branch, but it's easier to just merge this branch and printer-info since both are related to availability of data (I merged them a few minutes ago, working on fixing some lines).

**Comment by nicholaspad** [comment]
sounds good, thanks!!

**Pull request closed without merging**
